### ISSUE TITLE
Incorrect save

### ISSUE THREAD

**Issue by 456vv** [qiandongyq/cookie-bus#7] opened 2020-05-29 07:52 UTC
In incognito mode, create profile. Cookies in normal mode will be saved together.

**Comment by qiandongyq** [comment] 2020-05-29 13:54
@456vv Can you describe the steps to reproduce this issue?

**Comment by 456vv** [comment] 2020-05-29 14:33
Incognito mode is isolated, cookie-bus does not recognize it.

**Comment by 456vv** [comment] 2020-05-29 15:31
[2020_05_29_23_23_52_246.mp4.zip](https://github.com/qiandongyq/cookie-bus/files/4702707/2020_05_29_23_23_52_246.mp4.zip)

由于无法上传mp4文件。下载后，删除文件后缀名.zip。
cannot upload mp4 file. after download, delete the file extension “.zip”.

**Comment by qiandongyq** [comment] 2020-05-29 16:04
Thanks for the demo video. Incognito mode has its own store to save the cookies. The issue is that the `domain` looks like not save correctly. You can see in your video, one of the `BADDUID` domain is `pan.baidu.com`,  and the other one is `.baidu.com`. 

When you refresh the page after import the cookies. `BADDUID` does not exist on  `.baidu.com`, so it will assign a new one. That's my guess. I will have to take a look at this. 

Thank you so much for your help.

**Comment by qiandongyq** [comment] 2020-06-01 03:15
Fixed.

Solution:
Add the `keep the original domain` option to create/edit profiles.

This fix will be part of  `1.0.4` release along with other changes

**Closed by qiandongyq** 2020-06-01 03:15 UTC
Labels: bug
